version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb:/data/db
    logging:
      driver: "none"
  node:
    restart: always
    depends_on: 
      - mongo
    ports: 
      - "3000:3000"
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - /app/node_modules
      - ./:/app
    environment: 
      - MONGO_URI=mongodb://mongo:27017/t-stores
volumes:
  mongodb: